// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6gCGMju5dLOwIHBUIeZD-g2-SCHxL4EQ',
    appId: '1:1028611908463:web:18d306786de3df9bec7e9a',
    messagingSenderId: '1028611908463',
    projectId: 'taskmanager-68111',
    authDomain: 'taskmanager-68111.firebaseapp.com',
    storageBucket: 'taskmanager-68111.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ8Nij352qxMA_-ed7cJ9WWTskaaqaXPk',
    appId: '1:1028611908463:android:a04101e864b8e0e1ec7e9a',
    messagingSenderId: '1028611908463',
    projectId: 'taskmanager-68111',
    storageBucket: 'taskmanager-68111.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAB8D4ggRFwcbkZ9BvuTtoXMEaa-5li9uM',
    appId: '1:1028611908463:ios:338816d3211775b8ec7e9a',
    messagingSenderId: '1028611908463',
    projectId: 'taskmanager-68111',
    storageBucket: 'taskmanager-68111.appspot.com',
    iosClientId: '1028611908463-9qki5od29lf5e6sdjoss909voova01ho.apps.googleusercontent.com',
    iosBundleId: 'com.mamonov.taskManager',
  );
}
